# Helm Values Specific to Orders Microservice
configMapData:
  API_PORT: "31200"
  PORT_SERVER: "8080"

  DATABASE_HOST: customer-db
  DATABASE_PORT: "5432"
  DATABASE_NAME: "customer-database"
  DATABASE_USER: "postgres"
  DATABASE_DIALECT: "postgres"

secret:
  enabled: true
  data:
    DATABASE_PASSWORD: "MTIzNDU2"

image:
  repository: "045628470274.dkr.ecr.us-east-1.amazonaws.com/tech-challenge-lanchonete/customer"
  tag: "latest"

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

database:
  port: 5432
  exposedPort: 5433
  useStatefulSet: true
  image:
    repository: postgres
    tag: latest
  configMapData:
    POSTGRES_DB: "customer-database"
    POSTGRES_USER: "postgres"
    POSTGRES_PORT: "5433"
    VOLUME_DB_DATA: "/var/lib/postgresql/data"
  secretData:
    POSTGRES_PASSWORD: "MTIzNDU2"
